--RESTAURANTS
INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, CATEGORY) VALUES ('1', 'Ristorantino', 'ITALIAN');
INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, CATEGORY) VALUES ('2', 'Baretto', 'BAR');
INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, CATEGORY) VALUES ('3', 'Da Gino', 'PIZZA');

